export const REALRWA_ROUTES = {
  home: "/home",
  homeDetail: "/home/detail",
  market: "/market",
  tokenized: "/tokenized",
  kyc: "/kyc",
  staked: "/staked",
  stakedDetail: "/staked/detail",
  lending: "/lending",
  lendingDetail: "/lending/detail",
  reserveFund: "/reservefund",
  insurance: "/insurance",
  invitation: "/invitation",
  otc: "/otc",
  portfolioTrade: "/backEnd/myOrder/tradeOrder",
  portfolioStake: "/backEnd/myOrder/stakeOrder",
  portfolioLending: "/backEnd/myOrder/borrowOrder",
  portfolioReserveOrders: "/backEnd/myOrder/supplyOrder",
  balance: "/backEnd/token/Balance",
} as const;
